[package]
name = "gg"
version = "0.15.3"
description = "GG - Gui for JJ"
authors = ["Thomas Castiglione"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dev-dependencies]
tempfile = "3.10.1"
zip = "0.6"
assert_matches = "1.5"

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-codegen = "2.0.0-beta"
tauri-macros = "2.0.0-beta"
tauri-plugin = "2.0.0-beta"
tauri-runtime = "2.0.0-beta"
tauri-runtime-wry = "2.0.0-beta"
tauri-utils = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta"
tauri-plugin-log = "2.0.0-beta"

jj-lib = { version = "0.16.0", features = ["vendored-openssl", "watchman"] }
jj-cli = { version = "0.16.0", default-features = false, features = [
    "vendored-openssl",
] }

anyhow = "1.0.81"
clap = { version = "4.5.3", features = ["derive"] }
chrono = { version = "0.4.34", features = ["serde"] }
config = { version = "0.13.4", default-features = false, features = ["toml"] }
dirs = "5.0.1"
dunce = "1.0.4"
itertools = "0.12.1"
indexmap = "2.2.5"
futures-util = "0.3.30"
git2 = { version = "0.18.3", features = ["vendored-libgit2"] }
gix = { version = "0.61.0", default-features = false, features = [
    "index",
    "max-performance-safe",
] }
log = "0.4"
pollster = "0.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
ts-rs = { version = "7.1.1", features = ["chrono-impl"], optional = true }

[target."cfg(windows)".dependencies]
windows = { version = "0.54.0", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Console",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_Shell_PropertiesSystem",
] }
