[package]
name = "gg"
version = "0.14.1"
description = "GG - Gui for JJ"
authors = ["Thomas Castiglione"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta.0"

jj-lib = "0.14.0"
jj-cli = { version = "0.14.0", default-features = false }

anyhow = "1.0.79"
itertools = "0.12.1"
futures-util = "0.3.30"
pollster = "0.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0"
ts-rs = "7.1.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
