[package]
name = "gg"
version = "0.15.0"
description = "GG - Gui for JJ"
authors = ["Thomas Castiglione"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dev-dependencies]
tempfile = "3.10.1"
zip = "0.6"

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta"
tauri-plugin-log = "2.0.0-beta"

jj-lib = { version = "0.15.1", features = ["vendored-openssl"] }
jj-cli = { version = "0.15.1", default-features = false, features = [
    "vendored-openssl",
] }

anyhow = "1.0.79"
chrono = { version = "0.4.34", features = ["serde"] }
dunce = "1.0.4"
itertools = "0.12.1"
indexmap = "2.2.2"
futures-util = "0.3.30"
git2 = { version = "0.18.2", features = ["vendored-libgit2"] }
gix = { version = "0.58.0", default-features = false, features = [
    "index",
    "max-performance-safe",
] }
log = "^0.4"
pollster = "0.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.57"
ts-rs = { version = "7.1.1", features = ["chrono-impl"], optional = true }

[patch.crates-io]
muda = { git = "https://github.com/gulbanana/muda.git", branch = "tauri-9127" }
