[package]
name = "gg"
version = "0.14.1"
description = "GG - Gui for JJ"
authors = ["Thomas Castiglione"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-window-state = "2.0.0-beta.0"

jj-lib = { version = "0.14.0", features = ["vendored-openssl"] }
jj-cli = { version = "0.14.0", default-features = false, features = [
    "vendored-openssl",
] }

anyhow = "1.0.79"
chrono = { version = "0.4.34", features = ["serde"] }
itertools = "0.12.1"
futures-util = "0.3.30"
gix = { version = "0.56.0", default-features = false, features = [
    "index",
    "max-performance-safe",
] }
pollster = "0.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0"
ts-rs = { version = "7.1.1", features = ["chrono-impl"], optional = true }

[features]
custom-protocol = ["tauri/custom-protocol"] # required for tauri build/dev
