# 原json格式配置
# {
#   "productName": "gg",
#   "version": "0.29.0",
#   "identifier": "au.gulbanana.gg",
productName = "gg"
version = "0.29.0"
identifier = "au.gulbanana.gg"

#   "build": {
#     "beforeDevCommand": "npm run dev",
#     "devUrl": "http://localhost:6973",
#     "beforeBuildCommand": "npm run build",
#     "frontendDist": "../dist"
#   },
[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:6973"
beforeBuildCommand = "npm run build"
frontendDist = "../dist"

#   "app": {
#     "windows": [
#       {
#         "label": "main",
#         "title": "GG - Gui for JJ",
#         "decorations": true,
#         "resizable": true,
#         "focus": true,
#         "width": 1280,
#         "height": 720,
#         "visible": false,
#         "dragDropEnabled": false
#       }
#     ],
#     "security": {
#       "csp": null
#     }
#   },
[app]
[[app.windows]]
label = "main"
title = "GG - Gui for JJ"
decorations = true
resizable = true
focus = true
width = 1280
height = 720
visible = false
dragDropEnabled = false

[app.security]
# csp = null (在TOML中，null值通常省略或注释掉)

#   "bundle": {
#     "active": false,
#     "targets": "all",
#     "icon": [
#       "icons/32x32.png",
#       "icons/128x128.png",
#       "icons/128x128@2x.png",
#       "icons/icon.icns",
#       "icons/icon.ico"
#     ]
#   },
[bundle]
active = false
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

#   "plugins": {}
# }
[plugins]
# 空对象在TOML中表示为空section
