[gg]
# Check whether revisions are immutable (ancestor of immutable_heads()) when
# loading them; slow on large repositories. Even if disabled, immutability 
# checks will still be done if you attempt to rewrite history.
check-immutable = true
