// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

/**
 * Adds changes to the working copy which reverse the effect of the selected revisions
 */
export type BackoutRevisions = { ids: Array<RevId> };
