// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

/**
 * Makes a revision the working copy
 */
export type CheckoutRevision = { id: RevId };
