// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevId } from "./RevId";

/**
 * Creates a new revision between two changes and makes it the working copy
 */
export type CreateRevisionBetween = { after_id: CommitId; before_id: RevId };
