// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

/**
 * Creates a new revision and makes it the working copy
 */
export type CreateRevision = { parent_ids: Array<RevId> };
