// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

/**
 * Updates a revision's description
 */
export type DescribeRevision = { id: RevId; new_description: string; reset_author: boolean };
