// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Utility type used for platform-specific display
 */
export type DisplayPath = string;
