// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

/**
 * Creates a copy of the selected revisions with the same parents and content
 */
export type DuplicateRevisions = { ids: Array<RevId> };
