// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputField } from "./InputField";

export type InputRequest = { title: string; detail: string; fields: Array<InputField> };
