// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Utility type used to abstract crlf/<br>/etc
 */
export type MultilineString = { lines: Array<string> };
