// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeId } from "./ChangeId";
import type { CommitId } from "./CommitId";

/**
 * A pair of ids representing the ui's view of a revision.
 * The worker may use one or both depending on policy.
 */
export type RevId = { change: ChangeId; commit: CommitId };
