// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bookmark or tag name with metadata.
 */
export type StoreRef =
    | {
          type: "LocalBookmark";
          branch_name: string;
          has_conflict: boolean;
          /**
           * Synchronized with all tracking remotes
           */
          is_synced: boolean;
          /**
           * Actual and potential remotes
           */
          tracking_remotes: Array<string>;
          available_remotes: number;
          potential_remotes: number;
      }
    | {
          type: "RemoteBookmark";
          branch_name: string;
          remote_name: string;
          has_conflict: boolean;
          /**
           * Tracking remote ref is synchronized with local ref
           */
          is_synced: boolean;
          /**
           * Has local ref
           */
          is_tracked: boolean;
          /**
           * Local ref has been deleted
           */
          is_absent: boolean;
      }
    | { type: "Tag"; tag_name: string };
