// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayPath } from "./DisplayPath";

/**
 * Utility type used for round-tripping
 */
export type TreePath = { repo_path: string; relative_path: DisplayPath };
